version: "3.8"
services:
    web:
        build: .
        container_name: movies-app
        ports:
            - "${PORT}:3000"
        environment:
            POSTGRES_USER: ${PROD_PG_USERNAME}
            POSTGRES_PASSWORD: ${PROD_PG_PASSWORD}
            POSTGRES_DB: ${PROD_PG_DATABASE}
            POSTGRES_HOST: PROD_PG_HOST
            POSTGRES_PORT: PROD_PORT
        depends_on:
            - db

    db:
        image: postgres:14
        container_name: postgres-db
        environment:
            POSTGRES_USER: ${PROD_PG_USERNAME}
            POSTGRES_PASSWORD: ${PROD_PG_PASSWORD}
            POSTGRES_DB: ${PROD_PG_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
